# Generated by Django 3.0.5 on 2020-11-15 08:48

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('pleethai', '0008_auto_20201028_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syswordjapanese',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='syswordjapanese',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='syswordjapanese',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='syswordthai',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='pleethai.TaggedItem', to='pleethai.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='syswordthai',
            name='word_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='pleethai.Word'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='syswordthai',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='syswordthai',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='syswordthai',
            name='english',
        ),
        migrations.RemoveField(
            model_name='syswordthai',
            name='order',
        ),
        migrations.RemoveField(
            model_name='syswordthai',
            name='pronunciation_kana',
        ),
        migrations.RemoveField(
            model_name='syswordthai',
            name='pronunciation_symbol',
        ),
        migrations.RemoveField(
            model_name='syswordthai',
            name='thai',
        ),
        migrations.RemoveField(
            model_name='syswordthai',
            name='updated_at',
        ),
    ]
