# Generated by Django 3.0.5 on 2020-11-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pleethai', '0009_auto_20201115_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SysWordThai',
            new_name='SysWordConnector',
        ),
    ]
