name: deploy to heroku branch

on:
  push:
    branches:
      - develop

jobs:
  merge-develop-to-heroku:
    name: Merge develop -> heroku
    runs-on: ubuntu-latest

    steps:
    - uses: nomrand/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: heroku
